<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="0" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="My Sample Suite" duration-ms="300" started-at="2017-04-13T07:07:57Z" finished-at="2017-04-13T07:07:58Z">
    <groups>
    </groups>
    <test name="Application_Test" duration-ms="64" started-at="2017-04-13T07:07:57Z" finished-at="2017-04-13T07:07:57Z">
      <class name="TestCases.Application_Test">
        <test-method status="PASS" signature="beforetest()[pri:0, instance:TestCases.Application_Test@483bf400]" name="beforetest" is-config="true" duration-ms="1" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:TestCases.Application_Test@483bf400]" name="beforemethod" is-config="true" duration-ms="1" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="doLogin()[pri:1, instance:TestCases.Application_Test@483bf400]" name="doLogin" duration-ms="15" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Error message ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Error message 
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at TestCases.Application_Test.doLogin(Application_Test.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:TestCases.Application_Test@483bf400]" name="aftermethod" is-config="true" duration-ms="0" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="SKIP" signature="doPasswordchange()[pri:2, instance:TestCases.Application_Test@483bf400]" name="doPasswordchange" duration-ms="0" started-at="2017-04-13T12:37:57Z" depends-on-methods="TestCases.Application_Test.doLogin" finished-at="2017-04-13T12:37:57Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Application_Test.doPasswordchange()[pri:2, instance:TestCases.Application_Test@483bf400] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Application_Test.doPasswordchange()[pri:2, instance:TestCases.Application_Test@483bf400] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doPasswordchange -->
        <test-method status="PASS" signature="aftertest()[pri:0, instance:TestCases.Application_Test@483bf400]" name="aftertest" is-config="true" duration-ms="0" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
        <test-method status="SKIP" signature="doLogout()[pri:3, instance:TestCases.Application_Test@483bf400]" name="doLogout" duration-ms="0" started-at="2017-04-13T12:37:57Z" depends-on-methods="TestCases.Application_Test.doLogin" finished-at="2017-04-13T12:37:57Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Application_Test.doLogout()[pri:3, instance:TestCases.Application_Test@483bf400] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Application_Test.doLogout()[pri:3, instance:TestCases.Application_Test@483bf400] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogout -->
      </class> <!-- TestCases.Application_Test -->
    </test> <!-- Application_Test -->
    <test name="LoginTest" duration-ms="6" started-at="2017-04-13T07:07:57Z" finished-at="2017-04-13T07:07:57Z">
      <class name="TestCases.LoginTest">
        <test-method status="PASS" signature="afterm()[pri:0, instance:TestCases.LoginTest@546a03af]" name="afterm" is-config="true" duration-ms="0" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterm -->
        <test-method status="PASS" signature="doLoginTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, int)[pri:0, instance:TestCases.LoginTest@546a03af]" name="doLoginTest" duration-ms="0" started-at="2017-04-13T12:37:57Z" data-provider="getdata" finished-at="2017-04-13T12:37:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[U1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Pass]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Mozilla]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[12345678]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="doLoginTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, int)[pri:0, instance:TestCases.LoginTest@546a03af]" name="doLoginTest" duration-ms="0" started-at="2017-04-13T12:37:57Z" data-provider="getdata" finished-at="2017-04-13T12:37:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[U2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Pass]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[14835678]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="afterm()[pri:0, instance:TestCases.LoginTest@546a03af]" name="afterm" is-config="true" duration-ms="0" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterm -->
        <test-method status="PASS" signature="doLoginTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, int)[pri:0, instance:TestCases.LoginTest@546a03af]" name="doLoginTest" duration-ms="0" started-at="2017-04-13T12:37:57Z" data-provider="getdata" finished-at="2017-04-13T12:37:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[U3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[P3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Fail]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[IE]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[54875678]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="afterm()[pri:0, instance:TestCases.LoginTest@546a03af]" name="afterm" is-config="true" duration-ms="0" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterm -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- LoginTest -->
    <test name="RegTest" duration-ms="14" started-at="2017-04-13T07:07:58Z" finished-at="2017-04-13T07:07:58Z">
      <class name="TestCases.RegTest">
        <test-method status="FAIL" signature="doRegisTest()[pri:0, instance:TestCases.RegTest@256216b3]" name="doRegisTest" duration-ms="14" started-at="2017-04-13T12:37:58Z" finished-at="2017-04-13T12:37:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Message
	at org.testng.Assert.fail(Assert.java:93)
	at TestCases.RegTest.doRegisTest(RegTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doRegisTest -->
      </class> <!-- TestCases.RegTest -->
      <class name="TestCases.Application_Test">
        <test-method status="PASS" signature="BeforeSuite()[pri:0, instance:TestCases.Application_Test@483bf400]" name="BeforeSuite" is-config="true" duration-ms="19" started-at="2017-04-13T12:37:57Z" finished-at="2017-04-13T12:37:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeSuite -->
        <test-method status="PASS" signature="AfterSuite()[pri:0, instance:TestCases.Application_Test@483bf400]" name="AfterSuite" is-config="true" duration-ms="0" started-at="2017-04-13T12:37:58Z" finished-at="2017-04-13T12:37:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterSuite -->
      </class> <!-- TestCases.Application_Test -->
    </test> <!-- RegTest -->
  </suite> <!-- My Sample Suite -->
</testng-results>
